//
// This file was auto-generated from Animator assets in Unity Project MIC.
//

// <auto-generated />

namespace MeshApp.Animations
{
    using System;
    using Microsoft.Mesh.CloudScripting;
    using Microsoft.Mesh.CloudScripting.Declarations;

    [UserCreatable(false)]
    public class WalkrigAnimator : AnimationNode
    {

        protected WalkrigAnimator(in Guid ahandle, bool transfer)
        : base(ahandle, transfer)
        { }

        internal static WalkrigAnimator GetOrCreateInstance(in Guid cookie, bool transfer)
        {
            var result = GetOrCreateCloudObject(
                cookie,
                transfer,
                (handle, t) => new WalkrigAnimator(handle, transfer: t));

            return result as WalkrigAnimator;
        }
    }
}