//
// This file was auto-generated from Animator assets in Unity Project MIC.
//

// <auto-generated />

namespace MeshApp.Animations
{
    using System;
    using Microsoft.Mesh.CloudScripting;
    using Microsoft.Mesh.CloudScripting.Declarations;

    [UserCreatable(false)]
    public class NewAnimatorControllerAnimator : AnimationNode
    {

        protected NewAnimatorControllerAnimator(in Guid ahandle, bool transfer)
        : base(ahandle, transfer)
        { }

        internal static NewAnimatorControllerAnimator GetOrCreateInstance(in Guid cookie, bool transfer)
        {
            var result = GetOrCreateCloudObject(
                cookie,
                transfer,
                (handle, t) => new NewAnimatorControllerAnimator(handle, transfer: t));

            return result as NewAnimatorControllerAnimator;
        }
    }
}